import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import { join, resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

import { NFT_METADATA_SCHEMA, formatIssues, validateAgainstSchema } from '../server/metadataSchema';

/**
 * Guards the demo metadata tree, which is generated by
 * `scripts/generate-demo-metadata.mjs` and committed so that seeded testnet
 * tokens have a `metadata_uri` that actually resolves.
 *
 * Three failure modes are worth catching here rather than in a browser:
 *
 *   1. A document that does not satisfy the same schema the upload route
 *      enforces would render on a demo token and be rejected on a real one.
 *   2. A document pointing at artwork that is not in the tree produces a broken
 *      image, and the on-chain URI it was seeded with cannot be rewritten.
 *   3. A `metadata_uri` longer than the NFT contract's 512-byte cap could never
 *      have been minted, so the seed script would fail partway through.
 *
 * Staleness — the committed tree not matching the generator — is covered by
 * `pnpm demo:metadata:check` in CI, which needs no test.
 */

const APP_DIR = resolve(__dirname, '../../..');
const REPO_ROOT = resolve(APP_DIR, '../..');
const METADATA_DIR = join(REPO_ROOT, 'demo', 'metadata');
const COLLECTIONS_DIR = join(METADATA_DIR, 'collections');
const TOKENS_DIR = join(METADATA_DIR, 'tokens');

/** The cap enforced by the NFT contract's `validate_metadata_uri`. */
const MAX_METADATA_URI_BYTES = 512;

interface Attribute {
  traitType?: string;
  trait_type?: string;
  value: string;
  displayType?: string;
  display_type?: string;
}

interface DemoDocument {
  name: string;
  description?: string;
  imageUri?: string;
  externalUrl?: string;
  collectionId?: string;
  royalties?: number;
  attributes?: Attribute[];
}

function documents(dir: string): Array<{ file: string; doc: DemoDocument; raw: string }> {
  return readdirSync(dir)
    .filter((file) => file.endsWith('.json'))
    .sort()
    .map((file) => {
      const raw = readFileSync(join(dir, file), 'utf8');
      return { file, doc: JSON.parse(raw) as DemoDocument, raw };
    });
}

function attributeValue(doc: DemoDocument, name: string): string | undefined {
  return doc.attributes?.find((entry) => (entry.traitType ?? entry.trait_type) === name)?.value;
}

const collectionDocs = documents(COLLECTIONS_DIR);
const tokenDocs = documents(TOKENS_DIR);

describe('demo metadata', () => {
  it('ships at least one collection and one token', () => {
    // A silently empty directory would make every assertion below vacuous.
    expect(collectionDocs.length).toBeGreaterThan(0);
    expect(tokenDocs.length).toBeGreaterThan(0);
  });

  it.each(collectionDocs.map((entry) => [entry.file, entry] as const))(
    'collection %s satisfies the upload schema',
    (_file, entry) => {
      const issues = validateAgainstSchema(NFT_METADATA_SCHEMA, entry.doc);
      expect(formatIssues(issues)).toBe('');
    },
  );

  it.each(tokenDocs.map((entry) => [entry.file, entry] as const))(
    'token %s satisfies the upload schema',
    (_file, entry) => {
      const issues = validateAgainstSchema(NFT_METADATA_SCHEMA, entry.doc);
      expect(formatIssues(issues)).toBe('');
    },
  );

  it.each([...collectionDocs, ...tokenDocs].map((entry) => [entry.file, entry] as const))(
    '%s references artwork that exists in the tree',
    (_file, entry) => {
      const imageUri = entry.doc.imageUri;
      expect(imageUri, 'every demo document needs an image to render').toBeTruthy();

      // The URI must be a committed file served from this repository; anything
      // else reintroduces the third-party dependency the demo exists to avoid.
      const marker = '/demo/';
      const at = imageUri!.indexOf(marker);
      expect(at, `${imageUri} is not a repository-relative demo path`).toBeGreaterThan(-1);

      const relative = imageUri!.slice(at + 1);
      expect(existsSync(join(REPO_ROOT, relative)), `${relative} is missing`).toBe(true);
    },
  );

  it.each(tokenDocs.map((entry) => [entry.file, entry] as const))(
    'token %s has a metadata URI inside the contract length cap',
    (_file, entry) => {
      const bytes = Buffer.byteLength(entry.raw, 'utf8');
      // The cap applies to the URI String, not the document, but the URI is
      // derived from the file name and is always the shorter of the two.
      expect(bytes).toBeGreaterThan(0);

      const uri = `${'https://raw.githubusercontent.com/BezaMint/BezaMint/main'}/demo/metadata/tokens/${entry.file}`;
      expect(Buffer.byteLength(uri, 'utf8')).toBeLessThanOrEqual(MAX_METADATA_URI_BYTES);
    },
  );

  it('gives every collection the number of tokens its Pieces attribute claims', () => {
    for (const collection of collectionDocs) {
      const slug = collection.file.replace(/\.json$/, '');
      const declared = Number(attributeValue(collection.doc, 'Pieces'));
      expect(Number.isFinite(declared), `${slug} must declare a Pieces count`).toBe(true);

      const tokens = tokenDocs.filter((entry) => entry.file.startsWith(`${slug}-`));
      expect(tokens.length, `${slug} declares ${declared} pieces`).toBe(declared);
    }
  });

  it('records each collection royalty in basis points within the contract limit', () => {
    for (const collection of collectionDocs) {
      const bps = collection.doc.royalties;
      expect(typeof bps, `${collection.file} must carry royalties`).toBe('number');
      expect(bps!).toBeGreaterThanOrEqual(0);
      // `configure_royalty` rejects anything above 10000 (100%).
      expect(bps!).toBeLessThanOrEqual(10000);
    }
  });

  // `next/image` refuses to load a remote host that is not in
  // `images.remotePatterns`, and it does so at render time rather than at build
  // time -- so a seeded token with an unlisted host shows a broken image on a
  // live page. Coupling the demo documents to the allowlist here means adding a
  // new image host to the demo fails in CI instead of in a browser.
  it('allows every demo image host in the Next image allowlist', () => {
    const require_ = createRequire(__filename);
    const nextConfig = require_(join(APP_DIR, 'next.config.js')) as {
      images?: { remotePatterns?: Array<{ protocol?: string; hostname?: string }> };
    };
    const allowed = new Set(
      (nextConfig.images?.remotePatterns ?? [])
        .filter((pattern) => !pattern.protocol || pattern.protocol === 'https')
        .map((pattern) => pattern.hostname)
        .filter((hostname): hostname is string => Boolean(hostname)),
    );

    expect(allowed.size, 'no remote patterns configured').toBeGreaterThan(0);

    for (const entry of [...collectionDocs, ...tokenDocs]) {
      const hostname = new URL(entry.doc.imageUri!).hostname;
      expect(
        allowed.has(hostname),
        `${entry.file} points at ${hostname}, which next.config.js does not allow`,
      ).toBe(true);
    }
  });

  it('ties every token to a collection document that exists', () => {
    const slugs = new Set(collectionDocs.map((entry) => entry.file.replace(/\.json$/, '')));
    for (const token of tokenDocs) {
      const slug = token.file.replace(/-\d+\.json$/, '');
      expect(slugs.has(slug), `${token.file} names an unknown collection ${slug}`).toBe(true);
    }
  });
});
